### Pandas 300제 넘파이 문제 <hr> 

#### 001 ~ 010 <hr>

In [1]:
# 넘파이 임포트
import numpy as np

In [3]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [5]:
data = np.arange(100)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
data = np.arange(3,30,3)
data

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [10]:
data = np.arange(2,1000,2)
data

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208,
       210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234,
       236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260,
       262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286,
       288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312,
       314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338,
       340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 36

In [12]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [16]:
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2,3) # (행,열)


array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [21]:
arr = np.arange(3)
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

#### 011 ~ 020 <hr>


In [26]:
## 방법1
data = np.array([[0,1,2], [3,4,5]])
display(data)

## 방법2
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
## 방법1
np.ones(20, dtype=int).reshape(4,5)

## 방법2
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones(100, dtype=int).reshape(10,10) * 255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [40]:
## 방법1
np.zeros(12, dtype=int).reshape(3,4)

## 방법2
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [42]:
data = np.array([1,2,3], dtype=np.int32)
data

array([1, 2, 3], dtype=int32)

In [44]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [46]:
arr = np.array(['1', '2', '3'])
arr.dtype ## U1은 1바이트 문자열

dtype('<U1')

In [48]:
arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)

#### 021 ~ 030 <hr>

In [ ]:
arr = np.array([1.1, 2.1, 3.1]) ## 뒷자리는 버림
arr.astype(np.int32)

array([1, 2, 3], dtype=int32)

In [56]:
np.linspace(0,10, num=20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [60]:
arr = np.arange(9).reshape(3, 3)
arr[-1]

array([6, 7, 8])

In [65]:
arr = np.arange(9).reshape(3, 3)
arr[:,1]

array([1, 4, 7])

In [68]:
arr = np.arange(25).reshape(5, 5)
arr[3,2]

np.int64(17)

In [71]:
arr = np.arange(25).reshape(5, 5)
arr[1, 1:]

array([6, 7, 8, 9])

In [76]:
arr = np.arange(25).reshape(5, 5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [79]:
arr = np.arange(25).reshape(5, 5)
arr[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [85]:
arr = np.arange(25).reshape(5, 5)
arr[[0,4],::3]

array([[ 0,  3],
       [20, 23]])

#### 031 ~ 040 <hr>

In [88]:
data = [1, 2, 3]
np.array(data) * 10

array([10, 20, 30])

In [90]:
data = [1, 2, 3]
np.array(data) ** 2

array([1, 4, 9])

In [ ]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis=0) ## 0 = columns

array([12., 18.])

In [97]:
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.std(axis=1)

array([5., 1.])

In [104]:
a = np.arange(4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
np.matmul(a, b) ## *는 같은 위치만 계산해서 아님

array([[ 3,  4],
       [11, 16]])

In [107]:
arr = np.arange(9).reshape(3, 3)
display(arr.T)
arr

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [110]:
arr = np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [115]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [119]:
arr = np.arange(10)
ret = (arr > 3) & (arr < 7)
arr[ret]

array([4, 5, 6])

#### 041 ~ 050 <hr>

In [121]:
arr = np.array([-1, 2, -3, 4])
arr[arr<0]

array([-1, -3])

In [127]:
arr = np.array([-1, 2, -3, 4])
arr[arr < 0 ] = 0
arr

array([0, 2, 0, 4])

In [129]:
arr = np.array([-1, 2, -3, 4])
abs(arr)

array([1, 2, 3, 4])

In [131]:
arr = np.array([-1, 2, -3, 4])
arr[arr>=0] += 10
arr[arr<0] -= 10
arr

array([-11,  12, -13,  14])

In [135]:
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)
arr

[3, 4, 1, 2, 5]

In [137]:
arr = np.array([1, 2, 3, 4, 5])
arr.min()

np.int64(1)

In [139]:
arr = np.array([1, 2, 3, 4, 5])
arr.max()

np.int64(5)

In [142]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
## 방법1
arr.sort()
arr

## 방법2
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4]])

In [143]:
arr = np.array([ [1, 2], [3, 4] ])
arr.flatten()

array([1, 2, 3, 4])