### [ndarray 객체 생성]

In [9]:
## 모듈 로딩
import numpy as np

In [10]:
##============================================
## 함수: numpy.ones(shape,1) [기]float
##============================================
## numpy, ndarray 객체 생성
nparray01=np.ones((2,3,1,2))        #튜플로

## ndarray 속성
print('type(nparray01)=',type(nparray01))
print('nparray01.shape=',nparray01.shape)
print('nparray01.size=',nparray01.size)         ##원소수
print('nparray01.itemsize=',nparray01.itemsize) ##원소1개 저장에 사용하는 메모리 칸수(저장바이트수 )
print('nparray01.dtype=',nparray01.dtype)       ##원소의 타입
print(nparray01)

type(nparray01)= <class 'numpy.ndarray'>
nparray01.shape= (2, 3, 1, 2)
nparray01.size= 12
nparray01.itemsize= 8
nparray01.dtype= float64
[[[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]


 [[[1. 1.]]

  [[1. 1.]]

  [[1. 1.]]]]


In [11]:
## ======================================
## numpy.full(shape, n) : [기본] float
## ======================================
nparray01 = np.full((2,3), 7)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (2, 3)
nparray01.size        = 6
nparray01.itemsize    = 8
nparray01.dtype       = int64
[[7 7 7]
 [7 7 7]]


In [12]:
##============================================
## 함수: numpy.zeros_like(ndarray객체) [기]float
##       numpy.ones_like(ndarray객체) [기]float
##============================================
## numpy, ndarray 객체 생성
a=np.array([11,22])
nparray01=np.zeros_like(a)        
nparray02=np.ones_like(a)

## ndarray 속성
print('type(nparray01)=',type(nparray01))
print('nparray01.shape=',nparray01.shape)
print('nparray01.size=',nparray01.size)         ##원소수
print('nparray01.itemsize=',nparray01.itemsize) ##원소1개 저장에 사용하는 메모리 칸수(저장바이트수 )
print('nparray01.dtype=',nparray01.dtype)       ##원소의 타입
print(nparray01)


## ndarray 속성
print('type(nparray02)=',type(nparray02))
print('nparray02.shape=',nparray02.shape)
print('nparray02.size=',nparray02.size)         ##원소수
print('nparray02.itemsize=',nparray02.itemsize) ##원소1개 저장에 사용하는 메모리 칸수(저장바이트수 )
print('nparray02.dtype=',nparray02.dtype)       ##원소의 타입
print(nparray02)

type(nparray01)= <class 'numpy.ndarray'>
nparray01.shape= (2,)
nparray01.size= 2
nparray01.itemsize= 8
nparray01.dtype= int64
[0 0]
type(nparray02)= <class 'numpy.ndarray'>
nparray02.shape= (2,)
nparray02.size= 2
nparray02.itemsize= 8
nparray02.dtype= int64
[1 1]


In [13]:
## ======================================
## 함수: numpy.arange([start,]stop[,step]) : 1D(1차원) array
##      [기] start=0, step=1 
## ======================================
nparray01 = np.arange(5)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = int64
[0 1 2 3 4]


In [15]:
## ======================================
## 함수: numpy.arange([start,]stop,num=50,
#                     endpoint=True, reystep=False) 
#       : 1D(1차원) array
##      [기] start <= ~ <= stop 사이 num개 숫자 생성 
## ======================================
nparray01 = np.linspace(0,3,num=5)                 ## 0<=~<=3 범위에서 10개 숫자 생성
nparray01, step=np.linspace(0,3,num=5,retstep=True)  ##숫자 사이 간격값 반환

#숫자 사이 간격값
print('step     =',step)

## ndarray 속성
print('type(nparray01)       =', type(nparray01))    
print('nparray01.shape       =', nparray01.shape)    
print('nparray01.size        =', nparray01.size)        ## 원소 개수
print('nparray01.itemsize    =', nparray01.itemsize)    ## 원소 1개 저장 바이트 수
print('nparray01.dtype       =', nparray01.dtype)       ## 원소들의 타입
print(nparray01)

step     = 0.75
type(nparray01)       = <class 'numpy.ndarray'>
nparray01.shape       = (5,)
nparray01.size        = 5
nparray01.itemsize    = 8
nparray01.dtype       = float64
[0.   0.75 1.5  2.25 3.  ]


In [16]:
## ======================================
## 함수: numpy.empty(shape,dtype) 
#       : 1D(1차원) array float
##      초기화 되지않은 쓰레기값의 배열
## ======================================
arr=np.empty((3,4))

## ndarray 속성
print('arr.shape       =', arr.shape)      
print('arr.size        =', arr.size)        ## 원소 개수
print('arr.dtype       =', arr.dtype)       ## 원소들의 타입
print(arr)

arr.shape       = (3, 4)
arr.size        = 12
arr.dtype       = float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
